### ISSUE TITLE
[Bug] Bug Here

### ISSUE THREAD

**Issue by Voxeliorn** [localip/nitro-sniper#376]
### Describe the bug

it dosent work

### To Reproduce

1 ) cd : into the folder
2 ) run : ./main.sh
3 ) done

### Expected behavior

idk

### Please provide your snipers settings.

```javascript
why did it delete itself
```

### What platform are you seeing the problem on?

Local Computer

### Relevant log output if applicable.

```text
Installing packages, please wait...
Installed dependencies.
Cloning the latest sniper code...
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
Cloned latest version of the sniper.
Installing sniper dependencies...
Installed sniper dependencies.
Running sniper...
/home/voxeliorn/Desktop/nitro-sniper-main/src/index.js:87
   if (!res.body?.length) {
                 ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

**Comment by IShowLight-7777** [comment]
Maybe doing npm i helps???
